stages:
  - build
build:
  stage: build

  script:
    # Compile and name the binary as `hello`
    - go build -o ${CI_PROJECT_NAME}
    # Move to gitlab build directory
    - mv ./hello ${CI_PROJECT_DIR}

  artifacts:
    paths:
    - ./${CI_PROJECT_NAME}
